name: Build & Publish — Senior News Daily

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:
      extra_url:
        description: "Optional: fetch from this URL now (RSS or article)"
        required: false
        default: ""
      broaden_sites:
        description: "Include lifestyle (golf, travel, cooking, finance) feeds"
        required: false
        default: "true"
      filter_mode:
        description: "Filter mode: none | loose | strict"
        required: false
        default: "none"
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install "lxml[html_clean]"
          pip check
          python -c "import readability, lxml.html.clean; print('✅ readability + lxml_html_clean OK')"

      - name: Fetch feeds
        env:
          EXTRA_URL: ${{ github.event.inputs.extra_url }}
          BROADEN_SITES: ${{ github.event.inputs.broaden_sites }}
          FILTER_MODE: ${{ github.event.inputs.filter_mode }}
        run: python bot/fetch.py

      - name: Summarize
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-4o-mini
        run: python bot/summarize.py

      - name: Build site
        run: python bot/site_builder.py

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
